server:
  port: ${SERVER_PORT:6001}

spring:
  application:
    name: mas-campaign-server

  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop

  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:7004}

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:7001/eureka/}