server:
  port: ${CONFIG_SERVICE_PORT:7000}

spring:
  application:
    name: mas-config-service
  cloud:
    config:
      server:
        enabled: true
        native:
          search-locations: classpath:/config-files
  profiles:
    active: native
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:7002}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:7001}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS