server:
  port: ${NOTIFICATION_SERVICE_PORT:8002}


spring:
  application:
    name: mis-notification-service

  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:7002}

  #cloud:
  #  stream:
  #    bindings:
  #      input:
  #        destination: campaign-query # (internal) for communication with campaign module
  #      output:
  #        destination: notification-query # (external) for send notifications to customers
  #rabbitmq:
  #  username: ${RABBIT_MQ_USERNAME:admin}
  #  password: ${RABBIT_MQ_PASSWORD:admin}

  datasource:
    username: sa
    url: jdbc:h2:mem:notification-db
  jpa:
    hibernate:
      ddl-auto: create-drop


management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:7001}/eureka

api:
  rabbit-mq: # rabbit disabled on v2 version
    exchange:
      direct: ms.api.direct
      topic: ms.api.topic
    queue:
      campaign: ms.api.campaign-query
      notification: ms.api.notification-query
    routing-key:
      campaign: ms.api.campaign-routing-key
      notification: ms.api.notification-routing-key
  kafka:
    address: 127.0.0.1:9092
    group.id: ms-group
    topic:
      campaign: ms.api.campaign-topic
      notification: ms.api.notification-topic

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"